WARNING 2025-01-17 11:04:45,680 log 1132 11616 Not Found: /music/
WARNING 2025-01-17 11:04:45,681 basehttp 1132 11616 "GET /music/ HTTP/1.1" 404 28
WARNING 2025-01-17 11:05:21,556 log 16728 14280 Not Found: /music/1
WARNING 2025-01-17 11:05:21,557 basehttp 16728 14280 "GET /music/1 HTTP/1.1" 404 3542
WARNING 2025-01-17 11:06:57,386 log 12784 16636 Not Found: /music/1
WARNING 2025-01-17 11:06:57,387 basehttp 12784 16636 "GET /music/1 HTTP/1.1" 404 29
ERROR 2025-01-17 11:09:40,235 log 12784 3436 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\userapp\views.py", line 33, in post
    'age': request.data['age'],
           ~~~~~~~~~~~~^^^^^^^
KeyError: 'age'
ERROR 2025-01-17 11:09:40,239 basehttp 12784 3436 "POST /auth/sign-up/ HTTP/1.1" 500 100601
ERROR 2025-01-17 11:10:39,419 log 15544 17104 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\userapp\views.py", line 33, in post
    'age': request.data['age'],
           ~~~~~~~~~~~~^^^^^^^
KeyError: 'age'
ERROR 2025-01-17 11:10:39,423 basehttp 15544 17104 "POST /auth/sign-up/ HTTP/1.1" 500 100601
ERROR 2025-01-17 11:18:19,688 log 16532 15968 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\userapp\views.py", line 33, in post
    'age': request.data['age'],
           ~~~~~~~~~~~~^^^^^^^
KeyError: 'age'
ERROR 2025-01-17 11:18:19,691 basehttp 16532 15968 "POST /auth/sign-up/ HTTP/1.1" 500 100579
ERROR 2025-01-17 11:20:00,245 log 15364 13680 Internal Server Error: /auth/sign-up/
Traceback (most recent call last):
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\userapp\views.py", line 33, in post
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Projects\beat_ñloud\venv\Lib\site-packages\rest_framework\serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `age` is not valid for model `UserProfile` in `userapp.serializers.UserProfileSerializer`.
ERROR 2025-01-17 11:20:00,250 basehttp 15364 13680 "POST /auth/sign-up/ HTTP/1.1" 500 151912
